name: "✨ Feature request"
description: Sugira uma nova funcionalidade.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado pela sugestão! Preencha as informações abaixo.
  - type: textarea
    id: problem
    attributes:
      label: Problema/Contexto
      description: Qual problema essa feature resolve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
      description: Descreva a solução desejada.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Contexto adicional
    validations:
      required: false
